server:
  port: 8071
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: accounts-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: accounts-service
          uri: lb://account-service
          predicates:
            - Path=/user-service/**
        - id: accounts-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**

management:
  tracing:
    sampling:
      probability: 1.0