spring:
  application:
    name: account-service
  config:
    import: "optional:configserver:http://localhost:8088"
  jpa:
    showSql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  artemis:
    broker-url: tcp://localhost:61616
    mode: native
    user: admin
    password: admin

  datasource:
    url: jdbc:mysql://localhost:3306/fundmanagerapp
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    log-statement: true
management:
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8081
