spring:
  application:
    name: account-service
  config:
    import: "optional:configserver:http://localhost:8088"
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/fundmanagerapp
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0


